- name: base_link
  xyz: 0.00433012 0.0 0.02635
  mass: 0.05
  com: 0.00433012 0.0 0.02635
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: link_1
  xyz: 0.0 0.0 0.0251809
  mass: 0.05
  com: 0.0 0.0 0.0251809
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: link_2
  xyz: 0.0 0.0 0.02885
  mass: 0.05
  com: 0.0 0.0 0.02885
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: link_3
  xyz: 0.0138059 0.0 0.08125
  mass: 0.05
  com: 0.0138059 0.0 0.08125
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: link_4
  xyz: 0.02885 0.0 0.0
  mass: 0.05
  com: 0.02885 0.0 0.0
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: link_5
  xyz: 0.0251808 0.0 0.0
  mass: 0.05
  com: 0.0251808 0.0 0.0
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: link_6
  xyz: 0.032182 0.0 0.0
  mass: 0.05
  com: 0.032182 0.0 0.0
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: gripper_base_link
  xyz: 0.0293 0.0 0.00546
  mass: 0.05
  com: 0.0293 0.0 0.00546
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: gripper_left_link
  xyz: 0.0224 0.00114971 0.0001
  mass: 0.05
  com: 0.0224 0.00114971 0.0001
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------

- name: gripper_right_link
  xyz: 0.0224 -0.00114971 0.0001
  mass: 0.05
  com: 0.0224 -0.00114971 0.0001
  inertia:
    ixx: 0.00001
    iyy: 0.00001
    izz: 0.00001
  color: red

#---------------------------------------------------------------